services:
  db:
    image: postgres:15
    container_name: expense-tracker-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: expense_tracker
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    image: yuvaraj015/expense-tracker-backend:v1.0.0
    container_name: expense-tracker-backend
    ports:
      - "5000:5000"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: expense_tracker
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      JWT_SECRET: your_secret_key
    depends_on:
      db:
        condition: service_healthy

  frontend:
    image: yuvaraj015/expense-tracker-frontend:v1.0.0
    container_name: expense-tracker-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  pgdata: